spring:
  application:
    name: user-service
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080

feign:
  sentinel:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081